# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiowidget.ui'
#
# Created: Thu Jun  5 21:52:19 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(393, 55)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 55))
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.artistLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.artistLabel.setFont(font)
        self.artistLabel.setWordWrap(False)
        self.artistLabel.setObjectName("artistLabel")
        self.horizontalLayout_2.addWidget(self.artistLabel)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.titleLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.titleLabel.setFont(font)
        self.titleLabel.setWordWrap(False)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stateLabel = QtGui.QLabel(Form)
        self.stateLabel.setText("")
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout_2.addWidget(self.stateLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(13)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playpauseLabel = QtGui.QLabel(Form)
        self.playpauseLabel.setMaximumSize(QtCore.QSize(25, 25))
        self.playpauseLabel.setText("")
        self.playpauseLabel.setPixmap(QtGui.QPixmap(":/newicons/Icons/Sekkyumu-Developpers-Play-Blue-Button.ico"))
        self.playpauseLabel.setScaledContents(True)
        self.playpauseLabel.setObjectName("playpauseLabel")
        self.horizontalLayout_3.addWidget(self.playpauseLabel)
        self.durationLabel = QtGui.QLabel(Form)
        self.durationLabel.setObjectName("durationLabel")
        self.horizontalLayout_3.addWidget(self.durationLabel)
        self.seekSlider = phonon.Phonon.SeekSlider(Form)
        self.seekSlider.setIconVisible(False)
        self.seekSlider.setTracking(False)
        self.seekSlider.setObjectName("seekSlider")
        self.horizontalLayout_3.addWidget(self.seekSlider)
        self.playLabel = QtGui.QLabel(Form)
        self.playLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playLabel.setObjectName("playLabel")
        self.horizontalLayout_3.addWidget(self.playLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.artistLabel.setText(QtGui.QApplication.translate("Form", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", " - ", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.durationLabel.setText(QtGui.QApplication.translate("Form", "4:20", None, QtGui.QApplication.UnicodeUTF8))
        self.playLabel.setText(QtGui.QApplication.translate("Form", "0:35", None, QtGui.QApplication.UnicodeUTF8))

from PySide import phonon
import resourses.resourses_rc
